### ISSUE TITLE
When acceptor is defined on a model, no proposition is taken into account.

### ISSUE THREAD

**Issue by jshrt** [invisible-tech/samx#10]
Example:

```
Model('emails', {
 schema: {
  from: '',
   ...
  },
  acceptor: (accept, proposition, currentModel) => { accept(proposition) }
})
```

No `Propose('emails')(/* proposition */)` ever works.

**Comment by jshrt** [comment]
This was caused by #4, and it has escaped my review back then. Let's try to make our reviews tighter. We need to involve the rest of the team with samx.
@kewitz

**Comment by kewitz** [comment]
@jshrt shit. We used to have a lint rule that would check for shadowing variables.

**Comment by jshrt** [comment]
I think it is still there. I am not sure if the shadowed variable rule would have caught that we were returning a function instead of a function call. But as we progress, we are prone to make such errors, we might wanna test samx asap
